<?php
/**
 * StylesheetManager.php
 *
 * @package Automattic\MSM_Sitemap\Infrastructure\WordPress
 */

declare(strict_types=1);

namespace Automattic\MSM_Sitemap\Infrastructure\WordPress;

use Automattic\MSM_Sitemap\Domain\ValueObjects\Site;

/**
 * Manages MSM-specific stylesheet modifications and references.
 *
 * This class handles the integration with WordPress core stylesheets,
 * providing MSM-specific branding and namespace support.
 */
class StylesheetManager {

	/**
	 * Initialize stylesheet management.
	 */
	public static function setup(): void {
		// Filter core stylesheet to support MSM namespaces
		add_filter( 'wp_sitemaps_stylesheet_content', array( __CLASS__, 'modify_core_stylesheet' ) );
		add_filter( 'wp_sitemaps_stylesheet_index_content', array( __CLASS__, 'modify_core_index_stylesheet' ) );
	}

	/**
	 * Get XSL stylesheet reference for individual sitemaps.
	 *
	 * @return string XSL stylesheet reference for sitemap.
	 */
	public static function get_sitemap_stylesheet_reference(): string {
		return "\n" . '<?xml-stylesheet type="text/xsl" href="' . Site::get_home_url( '/wp-sitemap.xsl' ) . '"?>' . "\n";
	}

	/**
	 * Get XSL stylesheet reference for sitemap index.
	 *
	 * @return string XSL stylesheet reference for sitemap index.
	 */
	public static function get_index_stylesheet_reference(): string {
		return "\n" . '<?xml-stylesheet type="text/xsl" href="' . Site::get_home_url( '/wp-sitemap-index.xsl' ) . '"?>' . "\n";
	}

	/**
	 * Modify core sitemap stylesheet to support MSM namespaces and branding.
	 *
	 * @param string $xsl_content The original XSL content from WordPress core.
	 * @return string Modified XSL content for MSM.
	 */
	public static function modify_core_stylesheet( string $xsl_content ): string {
		$xsl_content = str_replace(
			esc_xml( __( 'This XML Sitemap is generated by WordPress to make your content more visible for search engines.' ) ),
			esc_xml( __( 'This XML Sitemap is generated by MSM Sitemap to make your content more visible for search engines.', 'msm-sitemap' ) ),
			$xsl_content
		);

		// Add MSM namespaces to the stylesheet
		$xsl_content = str_replace(
			'xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"',
			'xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:n="http://www.google.com/schemas/sitemap-news/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"',
			$xsl_content
		);

		$xsl_content = str_replace(
			'exclude-result-prefixes="sitemap"',
			'exclude-result-prefixes="sitemap n image"',
			$xsl_content
		);

		/**
		 * Filters the content of the MSM sitemap stylesheet.
		 *
		 * @since 1.5.0
		 *
		 * @param string $xsl_content Full content for the XML stylesheet.
		 */
		return apply_filters( 'msm_sitemaps_stylesheet_content', $xsl_content );
	}

	/**
	 * Modify core sitemap index stylesheet for MSM branding.
	 *
	 * @param string $xsl_content The original XSL content from WordPress core.
	 * @return string Modified XSL content for MSM.
	 */
	public static function modify_core_index_stylesheet( string $xsl_content ): string {
		$xsl_content = str_replace(
			esc_xml( __( 'This XML Sitemap is generated by WordPress to make your content more visible for search engines.' ) ),
			esc_xml( __( 'This XML Sitemap Index is generated by MSM Sitemap to make your content more visible for search engines.', 'msm-sitemap' ) ),
			$xsl_content
		);

		/**
		 * Filters the content of the MSM sitemap index stylesheet.
		 *
		 * @param string $xsl_content Full content for the XML stylesheet.
		 */
		return apply_filters( 'msm_sitemaps_stylesheet_index_content', $xsl_content );
	}
}
