<?php
/**
 * WP_Test_Sitemap_CPT
 *
 * @package Metro_Sitemap/unit_tests
 */

namespace Automattic\MSM_Sitemap\Tests;

use Metro_Sitemap;

/**
 * Unit Tests to confirm Sitemaps are properly handled for Custom Post Types
 *
 * @author Matthew Denton (mdbitz)
 */
class CPTTest extends TestCase {

	/**
	 * Custom Post Type
	 *
	 * @var string
	 */
	public const TEST_CPT = 'msm_stest';

	/**
	 * Initialize Test CPT
	 */
	public static function setupBeforeClass(): void {
		register_post_type(
			self::TEST_CPT,
			array(
				'labels'       => array(
					'name'          => __( 'Sitemaps' ),
					'singular_name' => __( 'Sitemap' ),
					),
				'public'       => false,
				'has_archive'  => false,
				'rewrite'      => false,
				'show_ui'      => true,  // TODO: should probably have some sort of custom UI
				'show_in_menu' => false, // Since we're manually adding a Sitemaps menu, no need to auto-add one through the CPT.
				'supports'     => array(
					'title',
				),
			)
		);

	}

	/**
	 * Initialize MSM_SiteMap_Test
	 */
	public function setUp(): void {
		parent::setUp();
		// 3 for Today, 1 in "draft" status.
		$this->add_a_post_for_today();
		$this->add_a_post_for_today();
		$this->add_a_post_for_today( 'draft' );

		// 1 for each day in last week for CPT.
		$this->add_a_post_for_each_of_the_last_x_days_before_today( 6, 'publish', self::TEST_CPT );

		// 1 CPT draft for a month ago.
		$this->add_a_post_for_a_day_x_months_ago( 1, 'draft', self::TEST_CPT );

		$this->assertPostCount( 10 );
	}

	/**
	 * Verify Custom Post Types don't have Sitemaps generated by default
	 */
	public function test_cpt_ignored_by_default(): void {
		$this->build_sitemaps();
		
		$this->assertSitemapCount( 1 );
		$this->assertIndexedUrlCount( 2 );
	}

	/**
	 * Verify Custom Post Types included when "msm_sitemap_entry_post_type"
	 * filter applied
	 */
	public function test_cpt_included_by_filter(): void
	{
		$this->add_test_filter( 'msm_sitemap_entry_post_type', array( $this, 'add_cpt_to_msm_sitemap' ) );

		$this->build_sitemaps();

		$this->assertSitemapCount( 7 );
		$this->assertIndexedUrlCount( 8 );
	}

	/**
	 * Filter hook to add TEST_CPT to Metro_Sitemap supported post types
	 *
	 * @param array $cpts Array of Post Types.
	 *
	 * @return array<string> Array of Post Types.
	 */
	public function add_cpt_to_msm_sitemap( array $cpts ): array
	{
		$cpts[] = self::TEST_CPT;
		return $cpts;
	}

}
