<?php
/**
 * WP_Test_Sitemap_CPT
 *
 * @package Metro_Sitemap/unit_tests
 */

namespace Automattic\MSM_Sitemap\Tests;

use Metro_Sitemap;

/**
 * Unit Tests to confirm Sitemaps are properly handled for Custom Post Types
 *
 * @author Matthew Denton (mdbitz)
 */
class CPTTest extends TestCase {

	/**
	 * Custom Post Type
	 *
	 * @var string
	 */
	public const TEST_CPT = 'msm_stest';

	/**
	 * Initialize Test CPT
	 */
	public static function setupBeforeClass(): void {
		register_post_type(
			self::TEST_CPT,
			array(
				'labels'       => array(
					'name'          => __( 'Sitemaps' ),
					'singular_name' => __( 'Sitemap' ),
					),
				'public'       => false,
				'has_archive'  => false,
				'rewrite'      => false,
				'show_ui'      => true,  // TODO: should probably have some sort of custom UI
				'show_in_menu' => false, // Since we're manually adding a Sitemaps menu, no need to auto-add one through the CPT.
				'supports'     => array(
					'title',
				),
			)
		);

	}

	/**
	 * Initialize MSM_SiteMap_Test
	 */
	public function setup(): void {
		// Create Multiple Posts across various Dates.
		$date = time();

		// 3 for Today, 1 in "draft" status
		$cur_day = date( 'Y', $date ) . '-' . date( 'm', $date ) . '-' . date( 'd', $date ) . ' 00:00:00';
		$this->create_dummy_post( $cur_day );
		$this->create_dummy_post( $cur_day );
		$this->create_dummy_post( $cur_day, 'draft' );

		// 1  for each day in last week for CPT
		for ( $i = 0; $i < 6; $i++ ) {
			$date = strtotime( '-1 day', $date );
			$cur_day = date( 'Y', $date ) . '-' . date( 'm', $date ) . '-' . date( 'd', $date ) . ' 00:00:00';
			$this->create_dummy_post( $cur_day, 'publish', self::TEST_CPT );
		}

		// 1 CPT draft for a  month ago
		$date = strtotime( '-1 month' );
		$cur_day = date( 'Y', $date ) . '-' . date( 'm', $date ) . '-' . date( 'd', $date ) . ' 00:00:00';
		$this->create_dummy_post( $cur_day, 'draft', self::TEST_CPT );

		$this->assertCount( 10, $this->posts );
		$this->build_sitemaps();

	}

	/**
	 * Verify Custom Post Types don't have Sitemaps generated by default
	 */
	public function test_cpt_ignored_by_default(): void
	{

		$this->build_sitemaps();
		$sitemaps = get_posts( array(
			'post_type' => Metro_Sitemap::SITEMAP_CPT,
			'fields' => 'ids',
			'posts_per_page' => -1,
		) );

		$this->assertCount( 1, $sitemaps );
		$this->assertEquals( 2, Metro_Sitemap::get_total_indexed_url_count() );
	}

	/**
	 * Verify Custom Post Types included when "msm_sitemap_entry_post_type"
	 * filter applied
	 */
	public function test_cpt_included_by_filter(): void
	{

		add_filter( 'msm_sitemap_entry_post_type', array( $this, 'add_cpt_to_msm_sitemap' ) );

		$this->build_sitemaps();
		$sitemaps = get_posts( array(
			'post_type' => Metro_Sitemap::SITEMAP_CPT,
			'fields' => 'ids',
			'posts_per_page' => -1,
		) );

		$this->assertCount( 7, $sitemaps );
		$this->assertEquals( 8, Metro_Sitemap::get_total_indexed_url_count() );
	}

	/**
	 * Filter hook to add TEST_CPT to Metro_Sitemap supported post types
	 *
	 * @param array $cpts Array of Post Types.
	 *
	 * @return array<string> Array of Post Types.
	 */
	public function add_cpt_to_msm_sitemap( array $cpts ): array
	{
		$cpts[] = self::TEST_CPT;
		return $cpts;
	}

}
