<?php
/**
 * WP_Test_Sitemap_Stats
 *
 * @package Metro_Sitemap/unit_tests
 */

namespace Automattic\MSM_Sitemap\Tests;

use Metro_Sitemap;

/**
 * Unit Tests to validate stats are properly generated by Metro_Sitemap
 *
 * @author michaelblouin
 * @author Matthew Denton (mdbitz)
 */
class StatsTest extends TestCase {

	/**
	 * Humber of Posts to Create (1 per year)
	 *
	 * @var Integer
	 */
	private int $num_years_data = 3;

	/**
	 * Generate posts and build initial sitemaps
	 */
	public function setup(): void {
		// Add a post for each day in the last x years.
		$dates = array();
		$date = time();
		for ( $i = 0; $i < $this->num_years_data; $i++ ) {
			// Add a post for x years ago.
			$dates[] = date( 'Y', $date ) . '-' . date( 'm', $date ) . '-' . date( 'd', $date ) . ' 00:00:00';
			$date = strtotime( '-1 year', $date );
		}

		$this->create_dummy_posts( $dates );

		$this->assertCount( $this->num_years_data, $this->posts );
		$this->build_sitemaps();
	}

	/**
	 * Verify that indexed URL count is calculated correctly
	 */
	public function test_site_stats_creation(): void
	{
		// Check that we've indexed the proper total number of URLs.
		$this->assertEquals( $this->num_years_data, Metro_Sitemap::get_total_indexed_url_count() );

		// Check specific stats.
		$this->assertTrue( $this->check_stats_for_created_posts() );
	}

	/**
	 * Checks that site stats are correct after inserting a new post on a day
	 * that already has a sitemap.
	 */
	public function test_site_stats_for_new_post(): void
	{
		$today_str = date( 'Y-m-d' );

		// Insert a new post for today.
		$this->create_dummy_posts( array( $today_str . ' 00:00:00' ) );

		// Build sitemaps.
		$this->build_sitemaps();

		// Check stats.
		$this->assertEquals( $this->num_years_data + 1, Metro_Sitemap::get_total_indexed_url_count() );

		// Check specific stats.
		$this->assertTrue( $this->check_stats_for_created_posts() );
	}

	/**
	 * Validate that Indexed URL Count is updated properly as posts are removed
	 */
	public function test_site_stats_for_deleted_post(): void
	{

		// Delete all posts (going backwards in time).
		$post_count = count( $this->posts );
		while ( $post_count ) {
			$last_post = array_pop( $this->posts );
			$post = wp_delete_post( $last_post['ID'], true );
			--$post_count;

			if ( $post instanceof \WP_Post ) {
				$this->update_sitemap_by_post( $post );
				$this->assertEquals( $post_count, Metro_Sitemap::get_total_indexed_url_count() );
				$this->assertTrue( $this->check_stats_for_created_posts() );
			}
		}

		$this->assertEquals( 0, Metro_Sitemap::count_sitemaps() );
		$this->assertEquals( 0, Metro_Sitemap::get_total_indexed_url_count() );
	}
}

