<?php
/**
 * WP_Test_Sitemap_Index
 *
 * @package Metro_Sitemap/unit_tests
 */

declare( strict_types=1 );

namespace Automattic\MSM_Sitemap\Tests\Integration;

use Metro_Sitemap;

/**
 * Unit Tests to validate indexes are properly generated by Metro_Sitemap.
 */
class IndexesTest extends TestCase {

	/**
	 * Create posts across a number of years
	 *
	 * @var int
	 */
	private int $num_years_data = 3;

	/**
	 * Generate posts and build initial sitemaps
	 */
	public function setUp(): void {
		parent::setUp();
		$this->add_a_post_for_each_of_the_last_x_years( $this->num_years_data );

		$this->assertPostCount( $this->num_years_data );
		$this->build_sitemaps();
	}

	/**
	 * Test that robots.txt has a single sitemap index when sitemaps by year are disabled
	 */
	public function test_single_sitemap_index(): void {
		// Turn on indexing by year
		remove_filter( 'msm_sitemap_index_by_year', '__return_true' );
		add_filter( 'msm_sitemap_index_by_year', '__return_false' );

		// Check that we have a single instance of sitemap.xml in robots.txt
		// We can't actually use the core function since it outputs headers,
		// but we only care about our stuff output to a public blog.
		preg_match_all( '|sitemap\.xml|', apply_filters( 'robots_txt', '', true ), $matches );

		// Check that we've indexed the proper total number of URLs.
		$this->assertCount( 1, $matches[0] );
	}

	/**
	 * Test that robots.txt has sitemap indexes for all years when sitemaps by year are enabled
	 */
	public function test_sitemap_index_by_year(): void {
		// Turn on indexing by year
		remove_filter( 'msm_sitemap_index_by_year', '__return_false' );
		add_filter( 'msm_sitemap_index_by_year', '__return_true' );

		// Check that we have a single instance of sitemap.xml in robots.txt
		// We can't actually use the core function since it outputs headers,
		// but we only care about our stuff output to a public blog.
		preg_match_all( '|sitemap-(\d{4})\.xml|', apply_filters( 'robots_txt', '', true ), $matches );

		// Check that we've indexed the proper total number of URLs.
		$this->assertCount( 3, $matches[0] );
	}
}
